### ISSUE TITLE
Non-static method Fahriztx\Zksoapphp\Fingerprint::connect() cannot be called statically

### ISSUE THREAD

**Issue by Wakil18** [FAHRIZTX/ZKSoapPHP#1]
When I try to initialize the connection using 

`$machine = Fingerprint::connect('192.168.1.175', '80', '123456');`

it gives me an error saying `Non-static method Fahriztx\Zksoapphp\Fingerprint::connect() cannot be called statically`.

So I did the following:

```
$machine = new Fingerprint;

 $machine->connect('192.168.1.175', '4370', '123456');
```

**Comment by sajib60web** [comment]
Data Not coming

**Comment by Wakil18** [comment]
I can't even establish a connection -_-

**Comment by sajib60web** [comment]
Connection is made but no data is received

**Comment by sajib60web** [comment]
Please sir solve it,

**Comment by sajib60web** [comment]
Very nice package

**Comment by FAHRIZTX** [comment]
> When I try to initialize the connection using
> 
> `$machine = Fingerprint::connect('192.168.1.175', '80', '123456');`
> 
> it gives me an error saying `Non-static method Fahriztx\Zksoapphp\Fingerprint::connect() cannot be called statically`.
> 
> So I did the following:
> 
> ```
> $machine = new Fingerprint;
> 
>  $machine->connect('192.168.1.175', '4370', '123456');
> ```

@Wakil18 what version of PHP are you using?

**Comment by Wakil18** [comment]
I'm using PHP 8.1.16. @FAHRIZTX
