### ISSUE TITLE
Connection is made but no data is received

### ISSUE THREAD

**Issue by sajib60web** [FAHRIZTX/ZKSoapPHP#2]
Please sir solve it,

**Comment by FAHRIZTX** [comment]
I think, maybe Your ComKey is wrong.

**Comment by FAHRIZTX** [comment]
![image](https://user-images.githubusercontent.com/23007278/225978077-04b7e2f4-9e61-4c2c-98ac-f9e59701eca9.png)

It works for me

**Comment by Ehtasham-CEF** [comment]
@FAHRIZTX its not. please see here: 
![image](https://github.com/FAHRIZTX/ZKSoapPHP/assets/142876819/e72a49b2-7150-4ca7-9553-1d7eb64340d1)
