### ISSUE TITLE
Not working on K40 model

### ISSUE THREAD

**Issue by prajapati-amit** [FAHRIZTX/ZKSoapPHP#4]

**Comment by FAHRIZTX** [comment]
* Have you enabled the TCP/IP access on the Fingerprint machine?
* Can you access the IP of your fingerprint on your browser (it will show Login Page WEB3.0)?
![image](https://github.com/FAHRIZTX/ZKSoapPHP/assets/23007278/8f434e44-0699-41c7-9177-082feef98bdc)
If you can access it, probably you wrong input the `comkey`.

**Comment by Ehtasham-CEF** [comment]
@FAHRIZTX whats your device model no? Mine is model zkteco f22. It connects but does not give data

**Comment by Ehtasham-CEF** [comment]
Also unable to access device IP in browser

**Comment by FAHRIZTX** [comment]
> Also unable to access device IP in browser

You can check on the device setting to enable it.

**Comment by Ehtasham-CEF** [comment]
@FAHRIZTX 
the settings are all set to a static IP configuration

**Comment by Ehtasham-CEF** [comment]
@FAHRIZTX 
what is this second requirement?
![image](https://github.com/FAHRIZTX/ZKSoapPHP/assets/142876819/3529b7bb-98f5-4db0-b4e4-1f5989433ab6)
